from __future__ import annotations

from datetime import datetime

from app.agents.state import AgentState, AgentTraceEvent, FinalReport


def _format_indicators_zh(ind: dict | None) -> str:
    if not ind:
        return "_技術指標資料不足_"
    rows = [
        ("收盤", ind.get("last_close")),
        ("MA5", ind.get("ma5")),
        ("MA20", ind.get("ma20")),
        ("MA60", ind.get("ma60")),
        ("RSI14", ind.get("rsi14")),
        ("乖離(20)", ind.get("bias_20")),
        ("動能 5D %", ind.get("momentum_5d_pct")),
        ("60D 高 / 低", f"{ind.get('high_60')} / {ind.get('low_60')}"),
    ]
    lines = ["| 指標 | 值 |", "|---|---|"]
    for label, val in rows:
        lines.append(f"| {label} | {val if val is not None else '-'} |")
    return "\n".join(lines)


def _format_indicators_en(ind: dict | None) -> str:
    if not ind:
        return "_insufficient price history_"
    rows = [
        ("Close", ind.get("last_close")),
        ("MA5", ind.get("ma5")),
        ("MA20", ind.get("ma20")),
        ("MA60", ind.get("ma60")),
        ("RSI14", ind.get("rsi14")),
        ("Bias(20)", ind.get("bias_20")),
        ("Momentum 5D %", ind.get("momentum_5d_pct")),
        ("60D High / Low", f"{ind.get('high_60')} / {ind.get('low_60')}"),
    ]
    lines = ["| Indicator | Value |", "|---|---|"]
    for label, val in rows:
        lines.append(f"| {label} | {val if val is not None else '-'} |")
    return "\n".join(lines)


async def reporter_node(state: AgentState) -> AgentState:
    trace: list[AgentTraceEvent] = list(state.get("trace") or [])
    analyst = state.get("analyst")
    if not analyst:
        return {
            **state,
            "report": FinalReport(markdown="# Report unavailable\n\nNo analyst output."),
            "trace": trace,
        }

    language = state.get("language", "zh-TW")
    ticker = state["ticker"]
    mode = state.get("mode", "on_demand")
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    ind_dict = analyst.indicators.model_dump() if analyst.indicators else None

    if language == "zh-TW":
        body = (
            f"# {ticker} — {analyst.headline}\n\n"
            f"_由 Compass Equity 多代理人系統生成 · {mode} 模式 · {timestamp}_\n\n"
            f"## 摘要\n\n{analyst.summary}\n\n"
            f"## 重點\n\n"
            + ("\n".join(f"- {b}" for b in analyst.bullets) if analyst.bullets else "_無_")
            + "\n\n## 技術指標\n\n"
            + _format_indicators_zh(ind_dict)
            + "\n"
        )
    else:
        body = (
            f"# {ticker} — {analyst.headline}\n\n"
            f"_Generated by Compass Equity multi-agent · {mode} mode · {timestamp}_\n\n"
            f"## Summary\n\n{analyst.summary}\n\n"
            f"## Key Points\n\n"
            + ("\n".join(f"- {b}" for b in analyst.bullets) if analyst.bullets else "_n/a_")
            + "\n\n## Indicators\n\n"
            + _format_indicators_en(ind_dict)
            + "\n"
        )

    risk = state.get("risk")
    if risk and risk.issues:
        if language == "zh-TW":
            body += "\n## 風險提示\n\n" + "\n".join(f"- {x}" for x in risk.issues) + "\n"
        else:
            body += "\n## Risk Notes\n\n" + "\n".join(f"- {x}" for x in risk.issues) + "\n"

    trace.append(AgentTraceEvent(agent="reporter", event="report_rendered"))

    return {
        **state,
        "report": FinalReport(markdown=body, citations=analyst.citations),
        "trace": trace,
    }
